{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flakey.fullname" . }}
  labels:
    {{- include "flakey.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
{{- end }}
---
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flakey.fullname" . }}-db
  labels:
    {{- include "flakey.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
  migration-password: {{ .Values.database.migrationPassword | quote }}
{{- end }}
---
{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) .Values.smtp.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flakey.fullname" . }}-smtp
  labels:
    {{- include "flakey.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-password: {{ .Values.smtp.password | quote }}
{{- end }}
