-- Index for the audit hash-chain ordered walk + append predecessor lookup.
--
-- The chain is ordered by id alone (the true per-org append order under the
-- advisory lock, see audit-chain.ts). Both the hot-path predecessor lookup
-- (logAudit: WHERE org_id = $1 AND entry_hash IS NOT NULL ORDER BY id DESC
-- LIMIT 1) and verifyAuditChain's keyset walk (WHERE org_id = $1 AND id > cursor
-- ORDER BY id ASC) want (org_id, id). The pre-existing idx_audit_log_org is
-- (org_id, created_at DESC), which does NOT serve an id-ordered scan.
--
-- CONCURRENTLY so building it on a populated production audit_log doesn't take a
-- write-blocking lock. This must be the ONLY statement in this file. CONCURRENTLY
-- cannot run inside a transaction block, so migrate.sh runs each file in
-- autocommit and the migrations smoke test splits CONCURRENTLY files on the
-- statement terminator. Keep this comment free of semicolons (the naive splitter
-- treats a comment semicolon as a statement break).
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_log_org_id ON audit_log (org_id, id);
