/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange email + password for tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user + personal org (when registration is enabled) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Registered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent runs (org-scoped) */
        get: {
            parameters: {
                query?: {
                    suite?: string;
                    branch?: string;
                    environment?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Run list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Ingest a test run
         * @description Accepts either a pre-normalized run (`{meta, stats, specs}`, as the
         *     first-class reporters send) or `{raw, meta}` for a vendor format the
         *     backend normalizes. `multipart/form-data` to `/runs/upload` is used when
         *     shipping artifacts; this JSON path is for results only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NormalizedRunInput"];
                };
            };
            responses: {
                /** @description Run created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get one run with its specs + tests */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Run detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a run (cascades to specs/tests/artifacts) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get one test with artifacts + navigation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Pass/fail timeline for a test across runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description History */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            title?: string;
                            full_title?: string;
                            file_path?: string;
                            history?: {
                                test_id?: number;
                                status?: components["schemas"]["TestStatus"];
                                duration_ms?: number;
                                error_message?: string | null;
                                run_id?: number;
                                suite_name?: string;
                                branch?: string;
                                /** Format: date-time */
                                created_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recurring failures grouped by error fingerprint
         * @description Returns the 100 most-recent error groups (by last_seen, then
         *     occurrence_count). The `status` filter is applied **before** that cap,
         *     so a status rarer than the 100 newest groups is not truncated. An
         *     unrecognised `status` value is ignored (no filter applied).
         */
        get: {
            parameters: {
                query?: {
                    suite?: string;
                    status?: components["schemas"]["ErrorStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Error groups */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorGroup"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors/{fingerprint}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fingerprint: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set the triage status of an error group (upsert) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fingerprint: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["ErrorStatus"];
                    };
                };
            };
            responses: {
                /** @description Status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: boolean;
                            group_id?: number;
                            status?: components["schemas"]["ErrorStatus"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/errors/{fingerprint}/tests": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fingerprint: string;
            };
            cookie?: never;
        };
        /** Tests affected by an error group */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fingerprint: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Affected tests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AffectedTest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors/{fingerprint}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fingerprint: string;
            };
            cookie?: never;
        };
        /** Notes on an error group */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fingerprint: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notes (oldest first) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorNote"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a note to an error group */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fingerprint: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        body: string;
                    };
                };
            };
            responses: {
                /** @description Note created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorNote"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flaky": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tests that alternate pass/fail */
        get: {
            parameters: {
                query?: {
                    suite?: string;
                    runs?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flaky tests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlakyTest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard statistics */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare two runs (newly-failed / fixed / flipped) */
        get: {
            parameters: {
                query: {
                    a: number;
                    b: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comparison */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary?: {
                                [key: string]: unknown;
                            };
                            comparisons?: {
                                [key: string]: unknown;
                            }[];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
        };
        /** @enum {string} */
        TestStatus: "passed" | "failed" | "skipped" | "pending";
        AuthResponse: {
            token?: string;
            refreshToken?: string;
            user?: {
                id?: number;
                /** Format: email */
                email?: string;
                name?: string | null;
            };
        };
        Run: {
            id: number;
            suite_name: string;
            branch?: string;
            commit_sha?: string;
            ci_run_id?: string;
            reporter?: string;
            /** Format: date-time */
            started_at?: string;
            /**
             * Format: date-time
             * @description null until the run merges/completes (live runs start with no finish time)
             */
            finished_at?: string | null;
            total: number;
            passed: number;
            failed: number;
            skipped: number;
            pending: number;
            duration_ms: number;
            /** Format: date-time */
            created_at?: string;
            spec_count?: number;
            spec_files?: string[] | null;
            new_failures?: number;
            aborted?: boolean;
            /** @description '' when no environment label is set (NOT NULL DEFAULT '') */
            environment?: string;
        };
        RunDetail: components["schemas"]["Run"] & {
            specs?: components["schemas"]["Spec"][];
            prev_id?: number | null;
            next_id?: number | null;
        };
        Spec: {
            id?: number;
            run_id?: number;
            file_path?: string;
            title?: string;
            total?: number;
            passed?: number;
            failed?: number;
            skipped?: number;
            pending?: number;
            duration_ms?: number;
            tests?: components["schemas"]["TestResult"][];
        };
        TestResult: {
            id: number;
            spec_id?: number;
            title: string;
            full_title: string;
            status: components["schemas"]["TestStatus"];
            duration_ms: number;
            error_message?: string | null;
            error_stack?: string | null;
            screenshot_paths?: string[];
            video_path?: string | null;
            test_code?: string | null;
            command_log?: {
                name?: string;
                message?: string;
                state?: string;
            }[] | null;
            snapshot_path?: string | null;
            failure_context?: components["schemas"]["FailureContext"] | null;
        };
        /** @description Cypress failure-context capture (Phase 13). */
        FailureContext: {
            commands_tail?: {
                name?: string;
                message?: string;
                state?: string;
            }[];
            browser_console?: string[];
            uncaught_errors?: string[];
            network_failures?: string[];
            retry_errors?: {
                attempt?: number;
                message?: string;
                stack?: string;
            }[];
            resolved_stack?: {
                file?: string;
                line?: number;
                column?: number;
                function?: string;
            }[];
            code_frame?: {
                file?: string;
                line?: number;
                column?: number;
                frame?: string;
            };
        };
        TestDetail: components["schemas"]["TestResult"] & {
            file_path?: string;
            run_id?: number;
            spec_title?: string;
            prev_failed_id?: number | null;
            next_failed_id?: number | null;
            failed_index?: number;
            failed_total?: number;
        };
        /**
         * @description Triage state of an error group. Unstamped groups default to `open`.
         * @enum {string}
         */
        ErrorStatus: "open" | "investigating" | "known" | "fixed" | "ignored";
        ErrorGroup: {
            fingerprint?: string;
            error_message?: string;
            occurrence_count?: number;
            affected_tests?: number;
            affected_runs?: number;
            /** Format: date-time */
            first_seen?: string;
            /** Format: date-time */
            last_seen?: string;
            latest_run_id?: number;
            latest_test_id?: number | null;
            test_titles?: string[];
            file_paths?: string[];
            suite_name?: string;
            group_id?: number | null;
            status?: components["schemas"]["ErrorStatus"];
            note_count?: number;
        };
        AffectedTest: {
            full_title?: string;
            title?: string;
            file_path?: string;
            suite_name?: string;
            occurrence_count?: number;
            /** Format: date-time */
            last_seen?: string;
            latest_test_id?: number;
            latest_run_id?: number;
        };
        ErrorNote: {
            id?: number;
            body?: string;
            /** Format: date-time */
            created_at?: string;
            user_name?: string | null;
            user_email?: string | null;
        };
        FlakyTest: {
            full_title?: string;
            file_path?: string;
            suite_name?: string;
            flaky_rate?: number;
            flip_count?: number;
            total_runs?: number;
        };
        DashboardStats: {
            automated?: {
                total_runs?: number;
                total_tests?: number;
                total_passed?: number;
                total_failed?: number;
                pass_rate?: number;
                recent_runs?: components["schemas"]["Run"][];
            };
            manual?: {
                [key: string]: unknown;
            };
        };
        /** @description A pre-normalized run as the first-class reporters POST it. */
        NormalizedRunInput: {
            meta: {
                suite_name: string;
                branch: string;
                commit_sha: string;
                ci_run_id: string;
                started_at: string;
                finished_at: string;
                reporter: string;
                release?: string;
                environment?: string;
            };
            stats: components["schemas"]["RunStats"];
            specs: {
                file_path: string;
                title: string;
                stats: components["schemas"]["RunStats"];
                tests: {
                    title: string;
                    full_title: string;
                    status: components["schemas"]["TestStatus"];
                    duration_ms: number;
                    error?: {
                        message?: string;
                        stack?: string;
                    };
                    screenshot_paths?: string[];
                    video_path?: string;
                    test_code?: string;
                    command_log?: {
                        [key: string]: unknown;
                    }[];
                    metadata?: {
                        [key: string]: unknown;
                    };
                    failure_context?: components["schemas"]["FailureContext"];
                }[];
            }[];
        };
        RunStats: {
            total: number;
            passed: number;
            failed: number;
            skipped: number;
            pending: number;
            duration_ms: number;
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found (or not visible to this org) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
